AWSTemplateFormatVersion: "2010-09-09"
Description: Cloud Platform LaB for Sarrilo
Resources:

  PlatformVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
      - Key: Customer
        Value: Sarrilo
      - Key: Name
        Value: Sarrilo Cloud Platform LaB